services:
  wol-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # PC 설정 데이터 영속성
      - ./data:/app/data
      # SSH 키 파일 마운트 (선택사항)
      - ./ssh_keys:/app/ssh_keys:ro
    networks:
      - wol-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wol-network:
    driver: bridge
