services:
  wol-service:
    build: .
    ports:
      - "80:8000"
    volumes:
      - wol-data:/app/data
      # - ./ssh_keys:/app/ssh_keys:ro  # SSH 키 파일 마운트 (선택사항)
    networks:
      - wol-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wol-network:
    driver: bridge

volumes:
  wol-data:
    driver: local
